# Generated by Django 4.2.23 on 2025-07-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_name',
        ),
    ]
