# Generated by Django 4.2.23 on 2025-08-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_expense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.TextField(null=True),
        ),
    ]
